
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compilador;

/** CUP generated interface containing symbol constants. */
public interface ParserSym {
  /* terminals */
  public static final int tk_op_aritm = 16;
  public static final int tk_digits = 4;
  public static final int tk_string = 2;
  public static final int tk_rightb = 8;
  public static final int tk_leftb = 7;
  public static final int tk_equal = 15;
  public static final int tk_while = 12;
  public static final int tk_coma = 9;
  public static final int tk_closep = 6;
  public static final int tk_main = 13;
  public static final int EOF = 0;
  public static final int tk_op_rel = 17;
  public static final int tk_if = 11;
  public static final int tk_id = 19;
  public static final int error = 1;
  public static final int tk_openp = 5;
  public static final int tk_const = 14;
  public static final int tk_op_log = 18;
  public static final int tk_return = 3;
  public static final int tk_pcoma = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tk_string",
  "tk_return",
  "tk_digits",
  "tk_openp",
  "tk_closep",
  "tk_leftb",
  "tk_rightb",
  "tk_coma",
  "tk_pcoma",
  "tk_if",
  "tk_while",
  "tk_main",
  "tk_const",
  "tk_equal",
  "tk_op_aritm",
  "tk_op_rel",
  "tk_op_log",
  "tk_id"
  };
}

